// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs3bsrmoteONdBbYnCJTm_S4GGk51XfrQ',
    appId: '1:1044070361155:web:b9f341c937f7f523b10cf6',
    messagingSenderId: '1044070361155',
    projectId: 'move-e517a',
    authDomain: 'move-e517a.firebaseapp.com',
    storageBucket: 'move-e517a.appspot.com',
    measurementId: 'G-7J08THQ9B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDX7HCYn3kFFvh_09LNFWFg9z-hYUKA8',
    appId: '1:1044070361155:android:7dc780e620af1b38b10cf6',
    messagingSenderId: '1044070361155',
    projectId: 'move-e517a',
    storageBucket: 'move-e517a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4Q_pRuiqEYwCOxJjHUMpakMwFtgPXyw',
    appId: '1:1044070361155:ios:04d2dfe5aa5a9987b10cf6',
    messagingSenderId: '1044070361155',
    projectId: 'move-e517a',
    storageBucket: 'move-e517a.appspot.com',
    iosClientId: '1044070361155-ktcnp8oi1j35mjl0kojda30lu14edksd.apps.googleusercontent.com',
    iosBundleId: 'br.com.Ari.move',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4Q_pRuiqEYwCOxJjHUMpakMwFtgPXyw',
    appId: '1:1044070361155:ios:04d2dfe5aa5a9987b10cf6',
    messagingSenderId: '1044070361155',
    projectId: 'move-e517a',
    storageBucket: 'move-e517a.appspot.com',
    iosClientId: '1044070361155-ktcnp8oi1j35mjl0kojda30lu14edksd.apps.googleusercontent.com',
    iosBundleId: 'br.com.Ari.move',
  );
}
